Problem Statement: The goal of this project is to predict the likelihood of an employee leaving the company based on their details and workplace factors. The dataset contains multiple features that may influence employee attrition, such as job role, tenure, performance, satisfaction, and other relevant attributes. The target variable is quit, where 0 indicates the employee stayed and 1 indicates the employee left. Using a Decision Tree model, we aim to analyze the factors affecting employee retention and classify employees as likely to stay or leave.

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv(r'C:\Users\Admin\Documents\Decision_Tree_Dataset\HR_file.csv')
df

,Satisfaction Level,Last Evaluation,Number of Projects,Monthly Hours,Total Time at the Company,Work Accidents,Quit the Company,Promoted in Last 5 yrs,Departments,salary,Management
0,0.38,0.53,2,157,3,0,1,0,sales,low,31
1,0.80,0.86,5,262,6,0,1,0,sales,medium,71
2,0.11,0.88,7,272,4,0,1,0,sales,medium,8
3,0.72,0.87,5,223,5,0,1,0,sales,low,68
4,0.37,0.52,2,159,3,0,1,0,sales,low,48
...,...,...,...,...,...,...,...,...,...,...,...
14994,0.40,0.57,2,151,3,0,1,0,support,low,49
14995,0.37,0.48,2,160,3,0,1,0,support,low,3
14996,0.37,0.53,2,143,3,0,1,0,support,low,5
14997,0.11,0.96,6,280,4,0,1,0,support,low,78
14998,0.37,0.52,2,158,3,0,1,0,support,low,99

In [4]:
df.shape

(14999, 11)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14999 entries, 0 to 14998
Data columns (total 11 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Satisfaction Level         14999 non-null  float64
 1   Last Evaluation            14999 non-null  float64
 2   Number of Projects         14999 non-null  int64
 3   Monthly Hours              14999 non-null  int64
 4   Total Time at the Company  14999 non-null  int64
 5   Work Accidents             14999 non-null  int64
 6   Quit the Company           14999 non-null  int64
 7   Promoted in Last 5 yrs     14999 non-null  int64
 8   Departments                14999 non-null  object
 9   salary                     14999 non-null  object
 10  Management                 14999 non-null  int64
dtypes: float64(2), int64(7), object(2)
memory usage: 1.3+ MB

In [6]:
df.describe(include ='all')

,Satisfaction Level,Last Evaluation,Number of Projects,Monthly Hours,Total Time at the Company,Work Accidents,Quit the Company,Promoted in Last 5 yrs,Departments,salary,Management
count,14999.000000,14999.000000,14999.000000,14999.000000,14999.000000,14999.000000,14999.000000,14999.000000,14999,14999,14999.000000
unique,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10,3,NaN
top,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,sales,low,NaN
freq,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4140,7316,NaN
mean,0.612834,0.716102,3.803054,201.050337,3.498233,0.144610,0.238083,0.021268,NaN,NaN,11.706780
std,0.248631,0.171169,1.232592,49.943099,1.460136,0.351719,0.425924,0.144281,NaN,NaN,25.300786
min,0.090000,0.360000,2.000000,96.000000,2.000000,0.000000,0.000000,0.000000,NaN,NaN,0.000000
25%,0.440000,0.560000,3.000000,156.000000,3.000000,0.000000,0.000000,0.000000,NaN,NaN,0.000000
50%,0.640000,0.720000,4.000000,200.000000,3.000000,0.000000,0.000000,0.000000,NaN,NaN,0.000000
75%,0.820000,0.870000,5.000000,245.000000,4.000000,0.000000,0.000000,0.000000,NaN,NaN,0.000000
max,1.000000,1.000000,7.000000,310.000000,10.000000,1.000000,1.000000,1.000000,NaN,NaN,100.000000

In [7]:
# checking for the duplicates 
df.duplicated().sum()

# there are 1463 duplicates

np.int64(1463)

In [8]:
# class specifications 
# 0 = didnt quit 
# 1 = quit the company

In [9]:
# removing the duplicates 

df.drop_duplicates(inplace = True,keep = 'first')

In [10]:
df.shape

# duplicates dropped successfully

(13536, 11)

In [11]:
df.select_dtypes(include = 'number').corr()

,Satisfaction Level,Last Evaluation,Number of Projects,Monthly Hours,Total Time at the Company,Work Accidents,Quit the Company,Promoted in Last 5 yrs,Management
Satisfaction Level,1.000000,0.105134,-0.145453,-0.027488,-0.121642,0.060776,-0.398124,0.023361,-0.325542
Last Evaluation,0.105134,1.000000,0.370048,0.354593,0.163015,-0.004773,0.007509,-0.011840,0.002827
Number of Projects,-0.145453,0.370048,1.000000,0.440893,0.233350,-0.005384,0.025014,-0.004420,0.011609
Monthly Hours,-0.027488,0.354593,0.440893,1.000000,0.163514,-0.015557,0.075095,-0.009233,0.053554
Total Time at the Company,-0.121642,0.163015,0.233350,0.163514,1.000000,-0.011853,0.207256,0.046509,0.169385
Work Accidents,0.060776,-0.004773,-0.005384,-0.015557,-0.011853,1.000000,-0.160142,0.033588,-0.132943
Quit the Company,-0.398124,0.007509,0.025014,0.075095,0.207256,-0.160142,1.000000,-0.049751,0.823648
Promoted in Last 5 yrs,0.023361,-0.011840,-0.004420,-0.009233,0.046509,0.033588,-0.049751,1.000000,-0.043083
Management,-0.325542,0.002827,0.011609,0.053554,0.169385,-0.132943,0.823648,-0.043083,1.000000

In [12]:
df['Management'].nunique()

101

In [13]:
df.shape

(13536, 11)

In [14]:
df['Management'].describe()

count    13536.000000
mean        12.829418
std         26.195403
min          0.000000
25%          0.000000
50%          0.000000
75%          4.000000
max        100.000000
Name: Management, dtype: float64

In [15]:
df.groupby('Management')['Quit the Company'].mean().head()

# The Management feature almost perfectly determines the target.
# This indicates data leakage, meaning:
# The feature contains information that is directly or indirectly derived from the target variable.

# so since this column is indirectly creating data leakage we need to drop this column

Management
0    0.003686
1    1.000000
2    1.000000
3    1.000000
4    1.000000
Name: Quit the Company, dtype: float64

In [16]:
# dropping the management and work accidents column 
df.drop(['Work Accidents','Management'],axis = 1,inplace = True)

In [17]:
df.columns 

# successfully dropped 'Work Accidents' and 'Management' columns

Index(['Satisfaction Level', 'Last Evaluation', 'Number of Projects',
       'Monthly Hours', 'Total Time at the Company', 'Quit the Company',
       'Promoted in Last 5 yrs', 'Departments ', 'salary'],
      dtype='object')

In [18]:
df.shape

(13536, 9)

In [19]:
# checking for the null values 
df.isnull().sum()

# so as we can see there are no missing values in the dataframe

Satisfaction Level           0
Last Evaluation              0
Number of Projects           0
Monthly Hours                0
Total Time at the Company    0
Quit the Company             0
Promoted in Last 5 yrs       0
Departments                  0
salary                       0
dtype: int64

In [20]:
# lets check the which time span has the largest no of enployees

tenure_count = df.groupby('Total Time at the Company').size()
tenure_count.sort_values(ascending = False)

# most of the employees  has stayed from 2 to 4 yrs

Total Time at the Company
3     5885
2     2931
4     2392
5     1405
6      641
10     107
7       94
8       81
dtype: int64

In [21]:
# Data Encoding 
from sklearn.preprocessing import LabelEncoder

le_dept = LabelEncoder()


df['Departments '] = le_dept.fit_transform(df['Departments '])

len_name_mapping = dict(zip(le_dept.classes_,le_dept.transform(le_dept.classes_)))

    

# len_name_mapping = dict(zip(le_dept.classes_,le_dept.transform(le_dept.classes_)))
print(len_name_mapping)

{'IT': np.int64(0), 'RandD': np.int64(1), 'accounting': np.int64(2), 'hr': np.int64(3), 'management': np.int64(4), 'marketing': np.int64(5), 'product_mng': np.int64(6), 'sales': np.int64(7), 'support': np.int64(8), 'technical': np.int64(9)}

In [22]:
len_name_mapping

{'IT': np.int64(0),
 'RandD': np.int64(1),
 'accounting': np.int64(2),
 'hr': np.int64(3),
 'management': np.int64(4),
 'marketing': np.int64(5),
 'product_mng': np.int64(6),
 'sales': np.int64(7),
 'support': np.int64(8),
 'technical': np.int64(9)}

In [23]:
df['Departments '].value_counts()

Departments
7    3691
9    2547
8    2057
0    1087
6     773
5     760
1     730
2     715
3     702
4     474
Name: count, dtype: int64

In [24]:
# encode the column salary using label encoder 

le_sal = LabelEncoder()

df['salary'] = le_sal.fit_transform(df['salary'])

le_name_mapping = dict(zip(le_sal.classes_,le_sal.transform(le_sal.classes_)))

print(le_name_mapping)

{'high': np.int64(0), 'low': np.int64(1), 'medium': np.int64(2)}

In [25]:
df['salary'].unique()

array([1, 2, 0])

In [26]:
df['Quit the Company'].value_counts()

Quit the Company
0    10000
1     3536
Name: count, dtype: int64

In [27]:
# Creating independent and dependent features

# Independent features
x = df.drop(['Quit the Company'],axis = 1)

# Dependent Features
y = df['Quit the Company']

In [28]:
x.columns

Index(['Satisfaction Level', 'Last Evaluation', 'Number of Projects',
       'Monthly Hours', 'Total Time at the Company', 'Promoted in Last 5 yrs',
       'Departments ', 'salary'],
      dtype='object')

In [29]:
y

0        1
1        1
2        1
3        1
4        1
        ..
14994    1
14995    1
14996    1
14997    1
14998    1
Name: Quit the Company, Length: 13536, dtype: int64

In [30]:
# checking the distribution 

print(x.shape)
print(y.shape)

(13536, 8)
(13536,)

In [31]:
# standardizing the features

from sklearn.preprocessing import StandardScaler

# creating a standardscaler object 
scaler = StandardScaler()

# Fitting the scaler to X to calculate mean and standard deviation for each feature 
scaler.fit(x)

# Transform x by scaling each feature to have mean = 0 and standard deviation = 1
x = scaler.transform(x)

In [32]:
from sklearn.model_selection import train_test_split 

x_train,x_test,y_train,y_test =train_test_split(x,y,test_size = 0.3,random_state = 42,stratify = y)

In [33]:
print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)

(9475, 8)
(9475,)
(4061, 8)
(4061,)

# Applying SMOTE

In [34]:
from imblearn.over_sampling import SMOTE

sm = SMOTE(random_state=42)
x_train_res,y_train_res = sm.fit_resample(x_train,y_train)

In [35]:
print(x_train_res.shape)
print(y_train_res.shape)

(14000, 8)
(14000,)

In [36]:
from sklearn.tree import DecisionTreeClassifier


model_DT = DecisionTreeClassifier(criterion = "entropy",random_state = 42)

# fit the model on taining data 
model_DT.fit(x_train,y_train)

# Using the trained model to predict the traget variable for the test set 
y_pred = model_DT.predict(x_test)

In [37]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report 

cfm = confusion_matrix(y_test,y_pred)
print(cfm)


# classification_report
print(classification_report(y_test,y_pred))

# accuracy_score 
print(accuracy_score(y_test,y_pred))

[[2948   52]
 [  32 1029]]
              precision    recall  f1-score   support

           0       0.99      0.98      0.99      3000
           1       0.95      0.97      0.96      1061

    accuracy                           0.98      4061
   macro avg       0.97      0.98      0.97      4061
weighted avg       0.98      0.98      0.98      4061

0.9793154395469096

In [38]:
# Now lets check the feture importance 

print(list(zip(df.columns[0:-1],model_DT.feature_importances_)))

[('Satisfaction Level', np.float64(0.3535594923687802)), ('Last Evaluation', np.float64(0.1406756478457451)), ('Number of Projects', np.float64(0.17515612190665006)), ('Monthly Hours', np.float64(0.08987094025598406)), ('Total Time at the Company', np.float64(0.21187592965522736)), ('Quit the Company', np.float64(0.0011306378595631519)), ('Promoted in Last 5 yrs', np.float64(0.0190617283939431)), ('Departments ', np.float64(0.008669501714106955))]

In [39]:
# lets check whether the model is overfit or not 

print(model_DT.score(x_train,y_train))
print(model_DT.score(x_test,y_test))

# so since the value of score of train data is 1 and the score of test data is 0.97 which is close to 1 
# so we can say that the model is not overfitted

1.0
0.9793154395469096